#!/bin/sh /etc/rc.common

START=99

start()
{
	if [ ! -d /tmp/log/sdutlogin ]; then
		mkdir -p /tmp/log/sdutlogin
	fi
	state=$(pgrep -f "/usr/lib/sdutlogin/login.sh")
	if [ -n "$state" ]; then
		restart
	else
		/usr/lib/sdutlogin/login.sh &
	fi
	echo "$(date "+%Y-%m-%d %H:%M:%S"): 已启动"
}

stop()
{
	kill -9 $(pgrep -f "/usr/lib/sdutlogin/login.sh") 2>/dev/null
	echo "$(date "+%Y-%m-%d %H:%M:%S"): 已停止"
}

restart()
{
	stop
	sleep 1
	start
}
