#!/bin/sh

# WAN 口 ifup 时触发登录检查

enable=$(uci -q get sdutlogin.@login[0].enable 2>/dev/null)
[ "$enable" != "1" ] && exit 0

if [ "$INTERFACE" = wan ] && [ "$ACTION" = ifup ]; then
	/etc/init.d/sdutlogin restart >/dev/null 2>&1
fi
exit 0
